import fs from "node:fs";
export function renderInputPage() {
  const font=fs.readFileSync("prototypes/evidence-consultation/fonts/NotoSansJP-japanese-400.woff2").toString("base64");
  const license=fs.readFileSync("prototypes/evidence-consultation/fonts/OFL-1.1.txt","utf8").replaceAll("<","&lt;");
  return `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';font-src data:;connect-src 'none';base-uri 'none';form-action 'none'">
  <title>資料から確認できる情報</title><style>
  @font-face{font-family:JP;src:url(data:font/woff2;base64,${font})}*{box-sizing:border-box}body{font:15px/1.8 JP,sans-serif;color:#243b30;background:#f4f7f4;margin:0;overflow-wrap:anywhere}main{max-width:850px;margin:auto;padding:18px}h1{font-size:25px;line-height:1.5}h2{font-size:21px}h3{font-size:17px}.notice{background:#e6f0e9;padding:14px;border-left:4px solid #36704f}label{display:block;margin:9px 0}input,select,textarea,button{font:inherit;max-width:100%;padding:8px;border:1px solid #9eb4a6;border-radius:6px}textarea{width:100%;min-height:90px}input[type=number]{width:85px}button{background:#285c40;color:white;cursor:pointer;margin:8px 5px 8px 0}article,.group,fieldset{background:white;border:1px solid #cbdad0;border-radius:9px;margin:15px 0;padding:14px;min-width:0}fieldset label{font-size:14px}p{margin:7px 0}.tag,small,.hash{font-size:12px}.age{display:flex;gap:7px;align-items:center;flex-wrap:wrap}blockquote{white-space:pre-wrap;margin:8px 0;padding:10px;background:#f1f5f2}dd{margin:0 0 8px}dt{font-weight:bold}details{border-top:1px solid #d4e0d8;padding:9px 0}summary{cursor:pointer}ul{padding-left:22px}.error{color:#913a28}.comparison{border-left:4px solid #60856d;padding:10px}pre{white-space:pre-wrap}a{color:#175e40}
  </style><main><p class="notice">非公開・隔離評価用の未承認資料です。通常経路には接続していません。AI回答や個別の健康判定ではありません。</p>
  <h1>資料から確認できる情報</h1>
  <section id="intake"><label>相談文<textarea id="question" maxlength="1000"></textarea></label>
  <label>相談の対象<select id="target"><option value="unknown">未指定</option><option value="child">子ども</option><option value="caregiver">保護者</option><option value="both">子どもと保護者</option></select></label>
  <div id="children"></div><button id="add-child" type="button">子どもを追加</button>
  <p>年齢はここに入力した値だけを使います。文章から年齢・診断・家族関係を補いません。月齢が分からない場合は空欄のままにできます。</p>
  <label><input type="checkbox" id="confirmed"> この対象と入力内容で検索することを確認しました</label>
  <label><input type="checkbox" id="age-ack"> 文章中の年齢と入力年齢に違いがある場合は、その違いを確認しました</label>
  <button type="button" id="search">資料を検索</button></section>
  <p id="status" role="status">相談文と対象条件を入力してください。</p><div id="results"></div>
  <footer><p>検索は保存済み語彙によるものです。検索の取りこぼしと資料不足は別です。一般的な自由文の意味理解、資料の自動追加、回答生成は行いません。</p><details><summary>同梱フォントのライセンス</summary><pre>${license}</pre></details></footer>
  </main><script>
  const h=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
  let count=0, health={}, sleep={}, revision=0;
  function addChild(){if(count>=4)return;count++;const div=document.createElement('div');div.className='age';div.dataset.child='c'+count;div.innerHTML='<strong>子ども'+count+'</strong><label><input type="number" min="0" max="100" class="years" aria-label="子ども'+count+'の年"> 歳</label><label><input type="number" min="0" max="11" class="months" aria-label="子ども'+count+'の月"> か月</label>';document.querySelector('#children').append(div)}
  function invalidate(){revision++;health={};sleep={};document.querySelector('#confirmed').checked=false;document.querySelector('#age-ack').checked=false;document.querySelector('#results').innerHTML='';document.querySelector('#status').textContent='対象または相談文が変わりました。追加条件と検索確認をリセットしました。'}
  const number=e=>e.value.trim()===''?null:Number(e.value);
  function input(){return{question:document.querySelector('#question').value,target:document.querySelector('#target').value,children:[...document.querySelectorAll('[data-child]')].map(e=>({id:e.dataset.child,years:number(e.querySelector('.years')),months:number(e.querySelector('.months'))})),health,confirmed:document.querySelector('#confirmed').checked,ageConflictAcknowledged:document.querySelector('#age-ack').checked}}
  function sleepForm(group){if(!group.hasSleep)return'';const s=sleep[group.id]||{};const checked=k=>s[k]===true?' checked':'';return'<fieldset class="sleep" data-group="'+h(group.id)+'"><legend>睡眠時間を比較する場合だけ入力</legend><p>1〜2歳（12か月以上36か月未満）の時間数の比較です。年齢は上の明示入力だけを使います。</p><label>夜の実睡眠 <input class="night" type="number" min="0" max="24" step="any" value="'+h(s.night??'')+'"> 時間</label><label>昼寝の実睡眠 <input class="nap" type="number" min="0" max="24" step="any" value="'+h(s.nap??'')+'"> 時間（昼寝なしと確認した場合は0）</label>'+[['sameDay','同じ1日分の記録です'],['actual','床にいた時間ではなく実際に眠った時間です'],['complete','その1日の睡眠を漏れなく記録しています'],['napIncluded','昼寝を含む合計として扱うことを確認しました'],['link','1〜2歳の昼寝込みの集計を説明する議事録を関連付ける']].map(([k,t])=>'<label><input type="checkbox" data-sleep="'+k+'"'+checked(k)+'> '+t+'</label>').join('')+'<button class="apply" type="button">明示した条件で再確認</button></fieldset>'}
  function healthForm(group){return group.healthPrompts.length?'<fieldset class="health" data-group="'+h(group.id)+'"><legend>検索された資料の対象条件（任意確認）</legend><p>一般的な研究情報を読むために診断の回答は必須ではありません。未確認のまま表示できます。</p>'+group.healthPrompts.map(p=>'<label>'+h(p.label)+'<select data-health="'+h(p.key)+'">'+[['unknown','未確認'],['present','ある'],['absent','ないと確認した']].map(([v,t])=>'<option value="'+v+'"'+((health[group.id]?.[p.key]||'unknown')===v?' selected':'')+'>'+t+'</option>').join('')+'</select><small>'+h(p.explanation)+'</small></label>').join('')+'<button class="apply" type="button">明示した条件で再確認</button></fieldset>':''}
  function comparison(g){if(!g.sleepResult)return'';const r=g.sleepResult;const status=r.comparison.status;return'<div class="comparison" data-comparison="'+h(status)+'"><strong>算術・目安比較・健康判断を分けます</strong><p>算術：'+(r.arithmetic.totalHours===null?'合計未確認':'約'+h(r.arithmetic.totalHours)+'時間')+'</p><p>目安比較：'+(status==='within_numeric_range'?'入力した時間数は昼寝込み11〜14時間の範囲内':status==='outside_numeric_range'?'入力した時間数は11〜14時間の範囲外':'保留（必要な明示条件が未確認、または対象外）')+'</p><p>十分か、健康上問題がないか、受診不要かは判断しません。</p></div>'}
  function itemHtml(i,g){const citation='<p class="item-citation"><a href="'+h(i.sourceUrl)+'">'+h(i.title)+'</a><br>該当箇所：'+h(i.sourceLocation)+'<br><small>出典 '+h(i.citation.sourceId)+' ／ 版 '+h(i.citation.version)+' ／ '+h(i.citation.versionId)+'</small></p>';const original='<p class="missing-fact">検索された原文に対応する事実データがありません。原文と必要な同版の文脈を表示します。</p><details class="missing-original"><summary>検索された原文と必要な文脈</summary><p>原文の該当箇所：'+h(i.sourceLocation)+'</p><blockquote data-root-original>'+h(i.originalText)+'</blockquote>'+i.requiredContext.map(c=>'<section class="required-context"><p>必要な文脈：'+h(c.role)+' ／ '+h(c.sourceLocation)+'<br><small>同じ出典版 '+h(i.citation.versionId)+' ／ 原文箇所 '+h(c.sectionId)+'</small></p><blockquote data-context-id="'+h(c.sectionId)+'">'+h(c.originalText)+'</blockquote></section>').join('')+'</details>';return'<div data-unit="'+h(i.unitId)+'"><p class="tag">'+h(i.unitId)+' ／ 資料採用・公開：未承認</p>'+citation+(i.missingFact?original:i.html.replaceAll('id="title-','id="'+h(g.id)+'-title-').replaceAll('aria-labelledby="title-','aria-labelledby="'+h(g.id)+'-title-'))+'</div>'}
  function display(result){document.querySelector('#status').textContent='検索状態：'+result.state+' ／ 隔離評価用・未承認';document.querySelector('#results').innerHTML=(result.ageNotice.message?'<p>'+h(result.ageNotice.message)+'</p>':'')+result.groups.map(g=>'<section class="group" data-result-group="'+h(g.id)+'"><h2>'+h(g.label)+'</h2><p>明示した月齢：'+(g.ageMonths===null?'未確認':h(g.ageMonths)+'か月')+'</p>'+(g.state==='no_vocabulary'?'<p class="search-gap">登録語彙に一致しません。検索の取りこぼしの可能性があり、資料不存在とは判断できません。</p>':'')+(!g.items.length&&g.state!=='no_vocabulary'?'<p class="no-matching">現在の検索語・明示条件で一致する結果はありません。対象条件による除外と資料不足は、この結果だけでは区別できません。</p>':'')+g.diagnostics.map(d=>'<p>'+h(d)+'</p>').join('')+healthForm(g)+sleepForm(g)+comparison(g)+(g.minutes?'<aside><p>別出典：<a href="'+h(g.minutes.url)+'">'+h(g.minutes.title)+'</a>。ガイド案の議事録であり、最終ガイドや独立した効果研究ではありません。利用は1〜2歳の集計範囲だけです。</p><p>'+h(g.minutes.attribution)+'</p><p>'+h(g.minutes.processingNotice)+'</p></aside>':'')+g.items.map(i=>itemHtml(i,g)).join('')+'</section>').join('');}
  async function search(){const current=revision;document.querySelector('#status').textContent='保存資料を検索しています…';try{if(typeof window.searchEvidenceBridge!=='function')throw Error('隔離検索の接続がありません。保存画面だけでは検索できません。');const result=await window.searchEvidenceBridge({input:input(),sleep});if(current!==revision)return;window.lastConnectionResult=result;display(result)}catch(e){document.querySelector('#status').textContent='検索できません：'+e.message;document.querySelector('#results').innerHTML='';}}
  document.querySelector('#search').onclick=search;
  document.querySelector('#add-child').onclick=()=>{addChild();invalidate()};
  document.querySelector('#intake').addEventListener('input',e=>{if(!['confirmed','age-ack'].includes(e.target.id))invalidate()});
  document.querySelector('#results').addEventListener('input',()=>{revision++;window.lastConnectionResult=null;for(const e of document.querySelectorAll('.comparison')){e.dataset.comparison='withheld';e.textContent='条件が変更されました。再確認まで比較は保留です。'}for(const e of document.querySelectorAll('#results aside'))e.hidden=true;document.querySelector('#status').textContent='追加条件を変更しました。明示した条件で再確認してください。'});
  document.querySelector('#results').addEventListener('click',e=>{if(!e.target.matches('.apply'))return;for(const f of document.querySelectorAll('.health')){health[f.dataset.group]=Object.fromEntries([...f.querySelectorAll('[data-health]')].map(s=>[s.dataset.health,s.value]))}for(const f of document.querySelectorAll('.sleep')){sleep[f.dataset.group]={night:number(f.querySelector('.night')),nap:number(f.querySelector('.nap')),...Object.fromEntries([...f.querySelectorAll('[data-sleep]')].map(c=>[c.dataset.sleep,c.checked]))}}search()});
  addChild();
  </script></html>`;
}