// Only the existing managed launcher may invoke this file.
import "../../../tests/safety/require-managed.mjs";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
const out="evidence-work/parent-reading-evaluation/retrieval-fact-connection-01";
const checks:any[]=[], cases:any[]=[], images:any[]=[];
const check=(name:string,condition:any)=>{assert(condition,name);checks.push({name,result:"PASS"})};
let browser:any,pool:any,temp:string|undefined,failure:any;
let externalRequests=0;
try {
  const {Pool}=await import("pg");
  const {initializePrototypeCorpus}=await import("../../../tests/fixtures/real-corpus/setup.mts");
  const {createConnection}=await import("./connection.mts");
  const {renderInputPage}=await import("./ui.mjs");
  const {chromium}=await import("playwright");
  // DATABASE_URL here is generated by the verified owner, never inherited from
  // the workspace. require-managed already proved its fingerprint/ancestry.
  pool=new Pool({connectionString:process.env.DATABASE_URL,max:2,connectionTimeoutMillis:5000});
  const initialized=await initializePrototypeCorpus(pool);
  check("Only E02/E03/E04 in temporary corpus",initialized.corpus.sources.size===3);
  const connection=await createConnection(pool,initialized);
  const states=await pool.query("SELECT publication_status, manual_reviewed, reviewer_name, reviewed_at FROM evidence_versions");
  check("Candidates remain draft and unreviewed",states.rows.length===3 && states.rows.every((r:any)=>
    r.publication_status==="draft" && r.manual_reviewed===false && r.reviewer_name===null && r.reviewed_at===null));
  check("Candidate sources remain draft with no published pointer",
    (await pool.query("SELECT status,current_published_version_id FROM evidence_sources")).rows.every((r:any)=>
      r.status==="draft"&&r.current_published_version_id===null));
  const normal=await connection.normalControl();
  check("Normal unchanged SQL cannot retrieve draft candidates",normal.results.length===0);
  const base=(question:string,years:number|null=1,months:number|null=8)=>({
    question,target:"child",children:[{id:"c1",years,months}],health:{},
    confirmed:true,ageConflictAcknowledged:true});
  const ask=async(name:string,input:any,sleep:any={})=>{
    const result=await connection.search({input,sleep});
    cases.push({name,input,sleep,result});
    return result;
  };
  const one=await ask("sleep-wording-one",base("睡眠時間の目安を知りたい"));
  const two=await ask("sleep-wording-two",base("睡眠の長さについて資料を見たい"));
  check("Paraphrases retrieve same source-bound fact",
    [one,two].every(r=>r.groups[0].items.some((i:any)=>i.factIds.includes("sleep-guidance"))));
  const lexical=await ask("known-sleep-lexical-miss",base("ねんねはどれくらい"));
  check("Known-source paraphrase miss remains vocabulary gap",lexical.groups[0].state==="no_vocabulary");
  const blank=await ask("age-unentered",base("睡眠時間の目安",null,null));
  check("Missing age is not zero",blank.groups[0].ageMonths===null);
  check("Missing age cannot compare",blank.groups[0].sleepResult?.comparison.performed===false);
  const outAge=await ask("age-outside-sleep-fact",base("睡眠時間",3,4));
  check("Shared original does not leak 1–2-year fact to 3-year unit",
    !outAge.groups[0].items.some((i:any)=>i.factIds.includes("sleep-guidance")));
  check("Retrieved logical unit without fact explicitly retained",
    outAge.groups[0].items.some((i:any)=>i.unitId==="E02-S02"&&i.missingFact));
  const noFactItem=outAge.groups[0].items.find((i:any)=>i.unitId==="E02-S02");
  check("Missing-fact payload retains same-version required context and locator",
    noFactItem.requiredContext.length>0 && noFactItem.sourceLocation && noFactItem.citation.versionId);
  const multiple=base("睡眠時間");multiple.children.push({id:"c2",years:4,months:0});
  const multi=await ask("multiple-children",multiple);
  check("Separate children preserve separate age and fact binding",
    multi.groups.length===2 && multi.groups[0].ageMonths===20 && multi.groups[1].ageMonths===48 &&
    multi.groups[0].hasSleep && !multi.groups[1].hasSleep);
  const both=await ask("children-and-caregiver",{...multiple,target:"both"});
  check("Both target keeps children and caregiver as three distinct groups",
    both.groups.length===3 && both.groups[2].id==="caregiver" && both.groups[2].ageMonths===null);
  const caregiver=await ask("caregiver-source-without-fact",{...base("保護者の睡眠"),target:"caregiver"});
  check("Caregiver age never borrowed from child",caregiver.groups[0].ageMonths===null);
  check("Caregiver source hit without manufactured fact",caregiver.groups[0].items.some((i:any)=>i.unitId==="E02-S03"&&i.missingFact));
  await ask("out-of-retained-corpus-feeding",base("離乳食を始める時期"));
  const relation=await ask("no-family-or-diagnosis-extraction",{...base("4歳の姉が発達障害です。親子のやりとりについて"),target:"unknown",children:[{id:"c1",years:null,months:null}]});
  check("Prose does not assign target or age",relation.groups.length===1&&relation.groups[0].id==="unknown"&&relation.groups[0].ageMonths===null);
  const research=await ask("interaction-information",base("親子のやりとりと育児支援",4,0));
  check("Research population mean is not individual age cutoff",research.groups[0].items.some((i:any)=>i.factIds.includes("interaction-results")));
  check("Health prompt comes from actual retrieved restrictions",research.groups[0].healthPrompts.length>0);
  const rawCase=await ask("case-id-is-not-dispatch",base("P01"));
  check("Case identifier is not a dispatch key",rawCase.groups[0].items.length===0);
  const supplied={night:10,nap:1,actual:true,sameDay:true,complete:true,napIncluded:true,link:true};
  const valid=await ask("sleep-explicit-comparison",base("睡眠時間"),{"child:c1":supplied});
  check("Explicit conditions permit numeric comparison only",valid.groups[0].sleepResult.comparison.status==="within_numeric_range"
    &&valid.groups[0].sleepResult.healthJudgment.status==="not_assessed");
  for(const [name,change] of Object.entries({unlink:{link:false},nightOnly:{nap:null},differentDay:{sameDay:false},
    timeInBed:{actual:false},incomplete:{complete:false},napUnconfirmed:{napIncluded:false}})){
    const result=await ask(name,base("睡眠時間"),{"child:c1":{...supplied,...change}});
    check(`${name}: comparison withheld`,!result.groups[0].sleepResult.comparison.performed);
  }
  temp=fs.mkdtempSync(path.join(os.tmpdir(),"retrieval-fact-ui-"));
  fs.writeFileSync(path.join(temp,"index.html"),renderInputPage());
  browser=await chromium.launch({executablePath:"/repl/tools/bin/chromium",
    args:["--disable-background-networking","--disable-component-update","--disable-sync","--host-resolver-rules=MAP * ~NOTFOUND"]});
  const context=await browser.newContext({offline:true,serviceWorkers:"block",viewport:{width:390,height:844}});
  await context.route("**/*",(route:any)=>{
    if(/^(file|data):/.test(route.request().url()))return route.continue();
    externalRequests++;return route.abort();
  });
  const page=await context.newPage();
  const errors:string[]=[];
  page.on("pageerror",(e:any)=>errors.push(e.message));
  await page.exposeBinding("searchEvidenceBridge",async(_source:any,payload:any)=>connection.search(payload));
  await page.goto(`file://${path.join(temp,"index.html")}`);
  await page.evaluate(()=>document.fonts.ready);
  const capture=async(name:string)=>{
    check(`${name}: no mobile overflow`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    const file=`${out}/${name}.png`;
    await page.screenshot({path:file,fullPage:true});
    images.push({name,path:file,sha256:createHash("sha256").update(fs.readFileSync(file)).digest("hex")});
  };
  const capturePart=async(name:string,selector:string,topOnly=false)=>{
    const locator=page.locator(selector).first();
    const file=`${out}/${name}.png`;
    if(topOnly){
      await locator.evaluate((element:HTMLElement)=>scrollTo(0,element.getBoundingClientRect().top+scrollY));
      // Capture the current 390×844 viewport beginning at this fact, rather
      // than mixing document coordinates with viewport screenshot clipping.
      await page.screenshot({path:file});
    }else await locator.screenshot({path:file});
    images.push({name,path:file,selector,cropped:true,
      sha256:createHash("sha256").update(fs.readFileSync(file)).digest("hex")});
  };
  await capture("input-empty");
  const uiSearch=async()=>{
    await page.locator("#confirmed").check();
    await page.locator("#search").click();
    await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.startsWith("検索状態"));
  };
  await page.locator("#question").fill("睡眠の長さについて資料を見たい");
  await page.locator("#target").selectOption("child");
  await page.locator(".years").fill("1");await page.locator(".months").fill("8");
  await capture("input-sleep");
  await uiSearch();
  check("Browser input really reaches SQL and fact renderer",await page.locator('[data-fact="sleep-guidance"]').count()===1);
  check("Sleep numbers are not prefilled",await page.locator(".night").inputValue()===""&&await page.locator(".nap").inputValue()==="");
  await capture("result-before-sleep-conditions");
  await page.locator(".night").fill("10");await page.locator(".nap").fill("1");
  for(const key of ["sameDay","actual","complete","napIncluded","link"])await page.locator(`[data-sleep="${key}"]`).check();
  await page.locator(".sleep .apply").click();
  await page.waitForSelector('[data-comparison="within_numeric_range"]');
  await capture("result-explicit-comparison");
  await capturePart("sleep-conditions-detail",".sleep");
  await capturePart("numeric-comparison-detail",".comparison");
  await capturePart("common-fact-top-detail","[data-fact]",true);
  check("Fact result includes generic direct source link and locator",
    await page.locator('[data-unit="E02-S01"] .item-citation a').getAttribute("href")===one.groups[0].items[0].sourceUrl
    && (await page.locator('[data-unit="E02-S01"] .item-citation').innerText()).includes(one.groups[0].items[0].sourceLocation));
  await page.locator('[data-sleep="link"]').uncheck();
  check("Changing additional input immediately invalidates prior comparison",
    await page.locator('[data-comparison="within_numeric_range"]').count()===0);
  await page.locator(".sleep .apply").click();
  await page.waitForSelector('[data-comparison="withheld"]');
  await capture("result-unlinked");
  await page.locator("#question").fill("親子のやりとりと育児支援");
  check("Question change clears results and confirmation",await page.locator(".group").count()===0&&!await page.locator("#confirmed").isChecked());
  await page.locator(".years").fill("4");await page.locator(".months").fill("0");
  await uiSearch();
  check("Browser asks only retrieved health conditions",await page.locator("[data-health]").count()>0);
  await capture("result-interactions");
  await page.locator("[data-health]").first().selectOption("absent");
  await page.locator(".health .apply").first().click();
  await page.waitForFunction(()=>document.querySelector("#status")?.textContent?.startsWith("検索状態"));
  await page.locator(".years").fill("5");
  check("Age change invalidates health confirmations",await page.locator("[data-health]").count()===0);
  await uiSearch();
  check("Health answer is unknown after age change",await page.locator("[data-health]").first().inputValue()==="unknown");
  await page.locator("#question").fill("ねんねはどれくらい");
  await uiSearch();await capture("result-search-gap");
  check("Search miss is not declared material absence",await page.locator(".search-gap").count()>0);
  await page.locator("#question").fill("睡眠時間");await page.locator(".years").fill("3");await page.locator(".months").fill("4");
  await uiSearch();await capture("result-source-without-fact");
  check("Browser explicitly marks missing fact data",await page.locator(".missing-fact").count()>0);
  await page.locator('[data-unit="E02-S02"] .missing-original summary').click();
  check("Missing fact root quote remains exact",
    await page.locator('[data-unit="E02-S02"] [data-root-original]').textContent()===noFactItem.originalText);
  check("Missing fact citation retains actual URL and locator",
    await page.locator('[data-unit="E02-S02"] .item-citation a').getAttribute("href")===noFactItem.sourceUrl &&
    (await page.locator('[data-unit="E02-S02"] .item-citation').innerText()).includes(noFactItem.sourceLocation));
  for(const context of noFactItem.requiredContext){
    check("Missing fact same-version context quote exact: "+context.sectionId,
      await page.locator('[data-unit="E02-S02"] [data-context-id="'+context.sectionId+'"]').textContent()===context.originalText);
    check("Missing fact context locator visible: "+context.sectionId,
      (await page.locator('[data-unit="E02-S02"] .missing-original').innerText()).includes(context.sourceLocation));
  }
  await capturePart("missing-fact-context-detail",'[data-unit="E02-S02"]');
  await page.locator(".years").fill("");await page.locator(".months").fill("");
  await uiSearch();await capture("result-age-unentered");
  check("Browser leaves explicit age unknown",await page.evaluate(()=>
    (window as any).lastConnectionResult.groups[0].ageMonths===null));
  await page.locator(".years").fill("1");await page.locator(".months").fill("8");
  await page.locator("#add-child").click();
  await page.locator('[data-child="c2"] .years').fill("4");await page.locator('[data-child="c2"] .months').fill("0");
  await page.locator("#target").selectOption("both");await uiSearch();
  await capture("result-multiple-targets");
  check("Browser has separate child and caregiver results",await page.locator("[data-result-group]").count()===3);
  await page.locator("#question").fill("離乳食を始める時期");await uiSearch();
  await capture("result-out-of-retained-scope");
  check("Unrelated subject does not manufacture facts",await page.locator("[data-fact]").count()===0);
  check("No browser script errors",errors.length===0);
  check("No browser external requests",externalRequests===0);
  const finalStates=await pool.query("SELECT publication_status,manual_reviewed FROM evidence_versions");
  check("Review/publication unchanged after interaction",finalStates.rows.every((r:any)=>r.publication_status==="draft"&&!r.manual_reviewed));
  check("Normal gate still excludes all candidates",(await connection.normalControl()).results.length===0);
  check("Real canonical SQL was used",connection.getSqlCalls()>0);
}catch(e:any){
  failure={message:String(e.message).replace(/postgres(?:ql)?:\/\/\S+/gi,"[redacted-dsn]"),
    stack:String(e.stack).replace(/postgres(?:ql)?:\/\/\S+/gi,"[redacted-dsn]")};
}finally{
  if(browser)await browser.close();
  if(pool)await pool.end();
  if(temp)fs.rmSync(temp,{recursive:true,force:true});
}
fs.writeFileSync(`${out}/verification.json`,JSON.stringify({
  result:failure?"FAILED":"PASSED",failure,checks,cases,images,externalRequests,
  newModelApiCalls:0,normalAppStarted:false,httpServerStarted:false,existingDatabaseAccess:false,
  candidateApprovalChanged:false,temporaryBrowserFilesRemoved:temp?!fs.existsSync(temp):true,
  ownedClusterCleanup:"Performed by unchanged outer owner finally; parent must check process exit and remaining owned directories."
},null,2)+"\n");
if(failure)throw Error("isolated retrieval connection verification failed; inspect credential-free verification.json");